import { Input } from "@/components/ui/input";
import uploadPic from "@/app/../../public/assets/upload.png";
import Image from "next/image";
import { Button } from "@/components/ui/button";
import { Avatar, AvatarFallback, AvatarImage } from "@/components/ui/avatar";
import Link from "next/link";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function HomeLayout({ children }) {
  return (
    <main className="h-screen w-screen overflow-auto md:overflow-hidden;g:overflow-hidden  flex flex-col">
      <nav className="flex items-center h-10 text-black justify-between gap-4  p-3 border-b-2 border-b-slate-200">
        <div className="flex flex-grow gap-4 items-center">
          <Link href="/app/home" className="font-logo font-extrabold ">
            Newton
          </Link>
        </div>

        <Button className="text-xs h-8 ">
          <Link href={"/app/paper/upload"}>upload</Link>
        </Button>
        <Avatar className="h-8 w-8 ">
          <AvatarImage src="https://github.com/shadcn.png" alt="@shadcn" />
          <AvatarFallback>CN</AvatarFallback>
        </Avatar>
        <></>
      </nav>
      {children}
    </main>
  );
}
